version: '3'
services:
  mysql-test:
    platform: linux/x86_64
    image: 'mysql:5.7.10'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
