export enum ResponseStatus {
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PHONE_CODE = 'INVALID_PHONE_CODE',
  ALREADY_EXIST_PHONE_NUMBER = 'ALREADY_EXIST_PHONE_NUMBER',
}
