export enum ResponseStatus {
  OK = 'OK',
  INTERNEL_SERVER_ERROR = 'INTERNEL_SERVER_ERROR',
  BAD_PARAMETERS = 'BAD_PARAMETERS',
  API_NOT_FOUND = 'API_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
